apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-vol01
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  hostPath:
    path: "/home/ravi/k8s/src"
