apiVersion: v1
kind: Service
metadata:
  name: weblogic-server-service
spec:
  selector:
    app: webapp
  ports:
  - name: weblogic
    port: 7001
    targetPort: 7001
    nodePort: 30005
  - name: weblog
    port: 9002
    targetPort: 9002
    nodePort: 30006

  type: NodePort
