apiVersion: v1
kind: Service
metadata:
  name: weblogic-server-new
spec:
  selector:
    app: webapp2
  ports:
  - name: weblog
    port: 7001
    targetPort: 7001
    nodePort: 30020
  - name: weblogs
    port: 9002
    targetPort: 9002
    nodePort: 30021
  type: NodePort
