apiVersion: v1
kind: Service
metadata:
  name: weblogic-server2
spec:
  selector:
    app: weblogicapp1
  ports:
  - name: weblogic
    port: 7001
    targetPort: 7001
    nodePort: 30010
  - name: weblog
    port: 9002
    targetPort: 9002
    nodePort: 30011
    
  type: NodePort
